### ISSUE TITLE
CSS works, JS doesn't.

### ISSUE THREAD

**Issue by appel** [gpbmike/refresh-sf#14]
Dropping css files into the input works fine, but dropping Javascript files does nothing. Tried it in Chrome 39.0.2171.95 m (also in incongnito mode), Firefox 34.0.5 and IE 11.0.9600. I'm on Windows 8.1.

**Comment by gpbmike** [comment]
Works fine for me. Can you post the file you're having trouble with somewhere?

**Comment by appel** [comment]
Sure, here's one, but have tried multiple .js files.
https://www.dropbox.com/s/l0owq66v422pabs/fittext.js

I'll check if I have the same problem on Ubuntu.

**Comment by appel** [comment]
Just tried it in Firefox on a vanilla Ubuntu 14.10 install, same problem unfortunately. I drag a .js file over the input box, it lights up blue, but when I drop it nothing happens.

**Comment by gpbmike** [comment]
Weird, I switched to my PC and I'm seeing the problem. I'm using https://github.com/bgrins/filereader.js/. I'll have to see why it works on their demo and not on my site. Thanks.

**Comment by appel** [comment]
Sure, no problem. Let me know if there's anything I can do to help. Just so you know, .css files seem to work fine.
