### ISSUE TITLE
Where's the output?

### ISSUE THREAD

**Issue by jdavies322** [gpbmike/refresh-sf#16]
Long time YUI user, first time at refresh-sf, and I am baffled by the interface. Once you paste your code into the Input text area, there's no button to initiate an action, and there's no output area or link. Clicking on the Javascript/CSS/HTML buttons above the input window just greys out the input and appears to do nothing. Same results in Safari 6, Firefox, Chrome.

Maybe it's just me overlooking something obvious?

**Comment by gpbmike** [comment]
You're clicking on the correct buttons. Heroku is occasionally pooping out on me and I'm trying to figure out why. I might just be exceeding the free tier. 

I should probably add a spinner or something that says "heroku is taking it's sweet time."

**Comment by gpbmike** [comment]
I added some feedback so it doesn't look frozen.
