### ISSUE TITLE
your www is redirecting

### ISSUE THREAD

**Issue by jawilco** [gpbmike/refresh-sf#21]
I had your site bookmark http://www.refresh-sf.com/ and it is redirecting to some search site: http://www.searchingresult.com/?pid=9POLWR59T&dn=refresh-sf.com&rpid=9PO6Q23IE .
It looks like http://refresh-sf.com/ without the www. is working fine. 

Love the site it has been very helpful over the years.

Thanks!

**Comment by gpbmike** [comment]
Thanks for the heads up. I made a change to my DNS settings. It should be fixed now.

**Comment by ThomasOrlita** [comment]
It looks like the www version isn't working...

**Comment by gpbmike** [comment]
I think this is working now.
