### ISSUE TITLE
CSS Background rules being rewritten into incompatible format with IE8

### ISSUE THREAD

**Issue by snetErz** [gpbmike/refresh-sf#23]
When working with backgrounds, the rules are being rewritten into a format that is not compatible with IE8. Testing it locally with a clean-css node plugin it does not convert the background parameters in this way.

Example:
	.test {
		background: url(../images/test.png) no-repeat center top;
	}
Becomes:
	.test{background:url(../images/test.png)center top no-repeat}

The space between the trailing parenthesis and "center" needs to be there for IE8 to function correctly.

**Comment by gpbmike** [comment]
I had mistakenly set the `compatibility` option for Clean-CSS to a boolean when it should have been a text field. You are free to now enter `ie8` in the `compatibility` option for expected result below:

```
.test{background:url(../images/test.png) center top no-repeat}
```

Thanks for reporting!
