### ISSUE TITLE
Download of original and compressed file?

### ISSUE THREAD

**Issue by q2apro** [gpbmike/refresh-sf#26]
Could bite my own ... I used http://gpbmike.github.io/refresh-sf/ to minimize one of my javascript files and copied the output to my original file, overwriting it (!) without any backup. 

So all my newly created code of today is gone. 

My questions: 
1. Can you provide a copy of the uploaded source? Even though it would be only for one day. 
2. How can you save me? (I guess the original code is still on your server?)

The code started with: 

    $(document).ready(function(){
    	
    	var recentValuesLink;
    	
    	var precision = 8;
    	var precisionD = Math.pow(10,precision);

Greetings,
Kai

Minimized file can be found here: http://jsfiddle.net/r0zvqb19/

**Update:** I found one backup copy, and it took me only 30 min to implement the missing stuff. Nevertheless, it would be great to have an answer on the question in case it happens again.

**Comment by gpbmike** [comment]
1. No, I do not keep, nor do I plan to keep, any user's code.
1. I cannot save you.
