### ISSUE TITLE
Gzip skips some characters. 

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [gpbmike/refresh-sf#28]
There's a bug in creation of gzip files. 

Suppose unminified file contains the + sign. 

style.min.css looks correct. 

style.min.css.gz skips the + character.

**Comment by vijayaraghavanramanan** [comment]
I wanna raise this issue again. 

This is especially important if the CSS file has unicode range in @font-face declarations.

**Comment by gpbmike** [comment]
When it comes to the Node side of the app, I don't really know what I'm doing. The code in question is here https://github.com/gpbmike/refresh-sf/blob/master/api/index.js#L223-L227

```javascript
api.post('/gz/:fileName', function (req, res) {
  zlib.gzip(req.body.code, function (_, result) {
    res.send(result);
  });
});
```

I would gladly accept a PR if you know what the fix is.

**Comment by vijayaraghavanramanan** [comment]
I will find out. 

clean-css of course has its own gzip compression which is:

`cat one.css two.css three.css | cleancss | gzip -9 -c > merged-minified-and-gzipped.css.gz
`

as per the read-me here: https://github.com/jakubpawlowicz/clean-css

Is that possible? Maybe it's better?

I have found that gzip using 7-zip compresses far better than the automatic one we get on refresh-sf. So maybe clean-css' built in compression is better since one can use level 9?

**Comment by gpbmike** [comment]
That command is using your system's `gzip` binary to do the compression. It's not part of cleancss.

**Comment by vijayaraghavanramanan** [comment]
If I understand correctly, there's some parsing here and it is being gzipped by zlib. Somewhere you may need to make a declaration that the character set is utf-8. Something like:

`req.setEncoding('utf8');`

**Comment by gpbmike** [comment]
I'll give that a shot when I have some time this weekend. Do you have a test case with sample input and expected output?

**Comment by vijayaraghavanramanan** [comment]
Yeah minfied output of this:

`/* greek-ext */
@font-face {
  font-family: 'Open Sans';
  font-style: normal;
  font-weight: 400;
  src: local('Open Sans'), local('OpenSans'), url(https://fonts.gstatic.com/s/opensans/v13/LWCjsQkB6EMdfHrEVqA1KRJtnKITppOI_IvcXXDNrsc.woff2) format('woff2');
  unicode-range: U+1F00-1FFF;
}
/* greek */
@font-face {
  font-family: 'Open Sans';
  font-style: normal;
  font-weight: 400;
  src: local('Open Sans'), local('OpenSans'), url(https://fonts.gstatic.com/s/opensans/v13/xozscpT2726on7jbcb_pAhJtnKITppOI_IvcXXDNrsc.woff2) format('woff2');
  unicode-range: U+0370-03FF;
}`

.css looks fine. plus sign in unicode-range present. However, .css.gz removes the plus sign.

**Comment by gpbmike** [comment]
I think I found the problem and fixed it with https://github.com/gpbmike/refresh-sf/commit/307428422c6758f581103a1a382eadcc9bc6973d.

**Comment by vijayaraghavanramanan** [comment]
Thanks Mike. 

Is it also possible to choose the best compression level 9? I think zlib default is 8. 

https://nodejs.org/api/zlib.html#zlib_zlib_creategzip_options instead of zlib.gzip needs to be used.
