### ISSUE TITLE
Mangle Top Level?

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [gpbmike/refresh-sf#31]
Feature request? Can we have mangling at the top level as an option for UglifyJS2? (Set to off by default of course).

Thanks, great site.

**Comment by gpbmike** [comment]
`toplevel` is now at the bottom of the uglifyjs options. defaults to false.

cheers.

**Comment by vijayaraghavanramanan** [comment]
Thanks! 

Pretty website, by the way.
