### ISSUE TITLE
How to replicate the config used on refresh-sf

### ISSUE THREAD

**Issue by mattpilott** [gpbmike/refresh-sf#37]
Hi,

I'm looking to mimic the output of css that is on refresh-sf in my projects. I am using clean-css with optimisation level 2 but cannot get my rules to merge. Here's a test case:

https://github.com/matt3224/remove-dupe-props-test

I wondered if you could give me a hand or the clean-css config you use?

Thanks,

**Comment by gpbmike** [comment]
Default options that I'm using are defined here: https://github.com/gpbmike/refresh-sf/blob/55f4bb97651bc980eb9ed074d150c1951a263582/app/scripts/options/cleancss.js

Good luck!
