### ISSUE TITLE
Problems with punc()

### ISSUE THREAD

**Issue by djrondon** [gpbmike/refresh-sf#38]
Hi Folks,
That was the error message:

{
  "message": "Unexpected token: punc ())",
  "filename": 0,
  "line": 160,
  "col": 2,
  "pos": 4963
}

The problem is on this part of the code:

nodes.push(
{id: 1, label: graph.data.name  , image: DIR + graph.data.image  , shape: 'image', value: 64 }, 
{id: 2, label: 'Acervo em 2016:\n ' + graph.data.acervo + ' Processos', image: DIR + 'acervo-blue.png', shape: 'image', value: 55 }, 
{id: 3, label: 'Distribuí­dos\n ' + graph.data.distribuidos  , image: DIR + 'recebido-blue.png', shape: 'image', value: 55 }, 
{id: 4, label: 'Baixados\n ' + graph.data.baixados , image: DIR + 'baixado-blue.png', shape: 'image', value: 55 }, 
{id: 5, label: 'Acervo Atual\n ' + graph.data.estoque , image: DIR + 'acervo-atual-blue.png', shape: 'image', value: 55}, 
{id: 6, label: 'Decisão', image: DIR + 'keyword.png', shape: 'image', value: 55},
  );

How can I fix this ?

Any clues?

Thanks in advance,

Cheers,

Rondon

**Comment by gpbmike** [comment]
That code looks okay to me. Try putting your source code in here: https://prettier.io/

It might give you a more specific error.
