### ISSUE TITLE
Compressor doesn't work: Unhandled error. :( 

### ISSUE THREAD

**Issue by Draghmar** [gpbmike/refresh-sf#40]
I have this for last couple of days: _Unhandled error. :(_ 
It shows up even on simplest code.

**Comment by gpbmike** [comment]
Hey there. I use Heroku as the backend and I'm out of free hours for the month.

**Comment by laukstein** [comment]
@gpbmike, maybe in such cause you can instead show relevant error text like "Unfortunately our server bandwidth has exceeded, try again in next month" ...

**Comment by gpbmike** [comment]
> you can instead show relevant error text

I sure could. You want to take a stab at it in a PR?

**Comment by laukstein** [comment]
@gpbmike if you are asking if I can fix this and other issue, I guess yes, if I find a time for it and a way to setup it on my environment for testing, and you give me permits to push it on repo. Also https://github.com/gpbmike/refresh-sf/issues/39 would require access to you DNS dashboard. I would recommend you to use Cloudflare.

**Comment by Draghmar** [comment]
@gpbmike Oh, ok. If the message was more clear I wouldn't bother you ;)

**Comment by gpbmike** [comment]
@Draghmar it's no bother. I haven't touched this repo in a long long time.
